@base_url = http://localhost:5000

# Create user
POST {{base_url}}/users
Content-Type: application/json

{
    "name": "Test",
    "email": "email@email.com"
}

###

# Get all users
GET {{base_url}}/users

###

# Get all accounts from user
GET {{base_url}}/accounts/email@email.com

###

PATCH  {{base_url}}/users/deactivate
Content-Type: application/json

{
    "email": "email@email.com"
}

###

# Add account
POST {{base_url}}/accounts
Content-Type: application/json

{
    "userEmail": "email@email.com"
}

###

@account_number = "64587008"

# Create deposit
POST {{base_url}}/accounts/deposit
Content-Type: application/json

{
    "accountNumber": {{account_number}},
    "amount": 100
}

###

# Create withdraw
POST {{base_url}}/accounts/withdraw
Content-Type: application/json

{
    "accountNumber": {{account_number}},
    "amount": 50
}

###

# Create transfer
@from_account_number = "64587008"
@to_account_number = "76804689"
POST {{base_url}}/accounts/transfer
Content-Type: application/json

{
    "fromAccountNumber": {{from_account_number}},
    "toAccountNumber": {{to_account_number}},
    "amount": 25
}


###

@account_balance=76804689

# Get balance
GET {{base_url}}/accounts/balance/{{account_balance}}


###

# Get history
GET {{base_url}}/accounts/history/{{account_balance}}
